### ISSUE TITLE
Downloading isn't working

### ISSUE THREAD

**Issue by TheKaram** [AmarnathCJD/gogram#129]
**Describe the bug**
If you try to download anything (i tried photo, music and document), you will notice that:
1. Downloading big files is extremely slow to start (same as the previous problem of uploading).
2. it crashes

**To Reproduce**
try to download any file.

**Expected behavior**
Download the file faster and without crashes.

**Desktop (please complete the following information):**
 - OS: ArchLinux

**Additional context**
This is the log:
```
2024/08/05 16:21:56 [info]  gogram [mtproto] - file - download: (photo_2024-08-05_16-21-55_214.jpg) - (51043) - (0)
2024/08/05 16:21:56 [info]  gogram [mtproto] - expected workers: 1, preallocated workers: 0
2024/08/05 16:21:56 [panic] gogram [client] - runtime error: invalid memory address or nil pointer dereference
 goroutine 14 [running]:

github.com/amarnathcjd/gogram/internal/utils.(*Logger).Panic(0xc000013d10, {0xc0001a5a28, 0x1, 0x1})
	/home/karam/go/pkg/mod/github.com/amarnathcjd/gogram@v0.0.0-20240805021614-b304fc2a8f02/internal/utils/logging.go:118 +0x68
github.com/amarnathcjd/gogram/telegram.(*Client).handleMessageUpdate.func1.(*Client).NewRecovery.1()
	/home/karam/go/pkg/mod/github.com/amarnathcjd/gogram@v0.0.0-20240805021614-b304fc2a8f02/telegram/client.go:558 +0x134
panic({0x7a5760?, 0xce13a0?})
	/usr/lib/go/src/runtime/panic.go:770 +0x132
github.com/amarnathcjd/gogram/telegram.(*Client).UploadGetFile(0xc00034c210?, 0xc0001a5d30?)
	/home/karam/go/pkg/mod/github.com/amarnathcjd/gogram@v0.0.0-20240805021614-b304fc2a8f02/telegram/methods_gen.go:16540 +0x12
github.com/amarnathcjd/gogram/telegram.(*Client).DownloadMedia(0xc0001f8000, {0x7d3c60, 0xc0001ced00}, {0xc0001a5ed0, 0x1, 0x4b4e01?})
	/home/karam/go/pkg/mod/github.com/amarnathcjd/gogram@v0.0.0-20240805021614-b304fc2a8f02/telegram/media.go:515 +0xbfa
github.c
```
And this is the code:
```go
func main() {
	client, err := telegram.NewClient(telegram.ClientConfig{
		AppID: 12345, AppHash: "",
	})
	if err != nil {
		log.Fatal(err)
	}
	client.LoginBot("")
	client.On(telegram.OnMessage, downloadMedia, telegram.FilterMedia)
	client.Idle() // block main goroutine until client is closed
}


func downloadMedia(msg *telegram.NewMessage) error {
	m, err := msg.Reply("Progress")
	if err != nil {
		fmt.Errorf(err.Error())
		return err
	}
	var pm *telegram.ProgressManager
	_, err = msg.Download(&telegram.DownloadOptions{
		FileName: msg.File.Name,
		ProgressCallback: func(a, b int32) {
			if pm == nil {
				pm = telegram.NewProgressManager(int(a), 1) // 3 is edit interval
			}
			if pm.ShouldEdit() {
				m.Edit(pm.GetStats(int(b)))
				fmt.Println(pm.GetStats(int(b)))
			}
		},
	})
	if err != nil {
		fmt.Errorf(err.Error())
		return err
	}
	_, err = m.Client.DeleteMessages(m.ChatID(), []int32{m.ID})
	if err != nil {
		fmt.Errorf(err.Error())
		return err
	}
	return nil
}
```

**Comment by AmarnathCJD** [comment]
Alright

**Comment by AmarnathCJD** [comment]
could you provide an update on this after using latest commit.

**Comment by TheKaram** [comment]
Unfortunately it didn't fix the issue

```
2024/08/05 19:41:03 [info]  gogram [mtproto] - file - download: (photo_2024-08-05_19-41-03_302.jpg) - (51043) - (0)
2024/08/05 19:41:03 [info]  gogram [mtproto] - expected workers: 1, preallocated workers: 0
2024/08/05 19:41:03 [panic] gogram [client] - runtime error: invalid memory address or nil pointer dereference
 goroutine 50 [running]:
github.com/amarnathcjd/gogram/internal/utils.(*Logger).Panic(0x400000fce0, {0x400019fa18, 0x1, 0x1})
        /home/ubuntu/go/pkg/mod/github.com/amarnathcjd/gogram@v0.0.0-20240805192016-a139b83e4d90/internal/utils/logging.go:118 +0x58
github.com/amarnathcjd/gogram/telegram.(*Client).handleMessageUpdate.func1.(*Client).NewRecovery.1()
        /home/ubuntu/go/pkg/mod/github.com/amarnathcjd/gogram@v0.0.0-20240805192016-a139b83e4d90/telegram/client.go:564 +0x11c
panic({0x379580?, 0x8b23e0?})
        /home/ubuntu/.local/share/mise/installs/go/1.22.5/src/runtime/panic.go:770 +0x124
github.com/amarnathcjd/gogram/telegram.(*Client).UploadGetFile(0x40000ba930?, 0x400019fd30?)
        /home/ubuntu/go/pkg/mod/github.com/amarnathcjd/gogram@v0.0.0-20240805192016-a139b83e4d90/telegram/methods_gen.go:16540 +0x18
github.com/amarnathcjd/gogram/telegram.(*Client).DownloadMedia(0x40001f4000, {0x3a7a80, 0x40001c6e00}, {0x400019fec8, 0x1, 0x2f15ec?})
        /home/ubuntu/go/pkg/mod/github.com/amarnathcjd/gogram@v0.0.0-20240805192016-a139b83e
```

**Comment by AmarnathCJD** [comment]
Eh, try delete the session.

**Comment by AmarnathCJD** [comment]
In the latest version I'm unable to reproduce the issue.

**Comment by TheKaram** [comment]
Ok, it works with a 3MB mp3, but for a 170MB video it reach 98% then panic with this error
```
2024/08/05 20:11:23 [info]  gogram [mtproto] - file - download: (video_2024-08-05_20-11-23_563.mp4) - (181632931) - (346)
2024/08/05 20:11:23 [info]  gogram [mtproto] - expected workers: 7, preallocated workers: 1
Progress: 0.29% | ETA: 5m45s | Speed: 311.40 KB/s
[                                                  ] 0%
...
Progress: 98.55% | ETA: 16s | Speed: 3.66 MB/s
[================================================= ] 98%
panic: sync: negative WaitGroup counter
goroutine 1191 [running]:
sync.(*WaitGroup).Add(0x40001c0c40?, 0x2b8270?)
        /home/ubuntu/.local/share/mise/installs/go/1.22.5/src/sync/waitgroup.go:62 +0x108
sync.(*WaitGroup).Done(...)
        /home/ubuntu/.local/share/mise/installs/go/1.22.5/src/sync/waitgroup.go:87
github.com/amarnathcjd/gogram/telegram.(*Client).DownloadMedia.func4.1()
        /home/ubuntu/go/pkg/mod/github.com/amarnathcjd/gogram@v0.0.0-20240805192016-a139b83e4d90/telegram/media.go:455 +0x48
github.com/amarnathcjd/gogram/telegram.(*Client).DownloadMedia.func4(0x1, 0x11f)        /home/ubuntu/go/pkg/mod/github.com/amarnathcjd/gogram@v0.0.0-20240805192016-a139b83e4d90/telegram/media.go:520 +0x4d0
created by github.com/amarnathcjd/gogram/telegram.(*Client).DownloadMedia in goroutine 68
        /home/ubuntu/go/pkg/mod/github.com/amarnathcjd/gogram@v0.0.0-20240805192016-a139b83e4d90/telegram/media.go:452 +0xc58
exit status 2
```

And for a 50kb jpg screenshot it keeps failing with this error 
```
2024/08/05 20:12:35 [info]  gogram [mtproto] - file - download: (photo_2024-08-05_20-12-35_372.jpg) - (51043) - (0)
2024/08/05 20:12:35 [info]  gogram [mtproto] - expected workers: 1, preallocated workers: 0
2024/08/05 20:12:35 [panic] gogram [client] - runtime error: invalid memory address or nil pointer dereference
 goroutine 30 [running]:
github.com/amarnathcjd/gogram/internal/utils.(*Logger).Panic(0x400019fd10, {0x400021da18, 0x1, 0x1})
        /home/ubuntu/go/pkg/mod/github.com/amarnathcjd/gogram@v0.0.0-20240805192016-a139b83e4d90/internal/utils/logging.go:118 +0x58
github.com/amarnathcjd/gogram/telegram.(*Client).handleMessageUpdate.func1.(*Client).NewRecovery.1()
        /home/ubuntu/go/pkg/mod/github.com/amarnathcjd/gogram@v0.0.0-20240805192016-a139b83e4d90/telegram/client.go:564 +0x11c
panic({0x3694e0?, 0x8a23e0?})
        /home/ubuntu/.local/share/mise/installs/go/1.22.5/src/runtime/panic.go:770 +0x124
github.com/amarnathcjd/gogram/telegram.(*Client).UploadGetFile(0x40001ac960?, 0x400021dd30?)
        /home/ubuntu/go/pkg/mod/github.com/amarnathcjd/gogram@v0.0.0-20240805192016-a139b83e4d90/telegram/methods_gen.go:16540 +0x18
github.com/amarnathcjd/gogram/telegram.(*Client).DownloadMedia(0x400028a000, {0x3979e0, 0x400031e3a0}, {0x400021dec8, 0x1, 0x2ee8fc?})
        /home/ubuntu/go/pkg/mod/github.com/amarnathcjd/gogram@v0.0.0-20240805192016-a139b83e
```

As you see this is the latest commit and I have deleted old session and cache.db.
All files are DC4, i don't know if this is useful to know

**Comment by TheKaram** [comment]
These are the logs

[logs-video.txt](https://github.com/user-attachments/files/16504932/logs-video.txt)
[logs-screenshot.txt](https://github.com/user-attachments/files/16504950/logs-screenshot.txt)

**Comment by AmarnathCJD** [comment]
I was able to replcate the -ve wg error in a linux server
added lock for sender.buzy field and it gone from there too

can you try now.

**Comment by AmarnathCJD** [comment]
expected workers: 1, preallocated workers: 0
2024/08/06 03:46:38 [0;35m[debug][0m gogram [mtproto] - downloading last part -1/0 in chunks of 49
2024/08/06 03:46:38 [0;35m[debug][0m gogram [client] - creating exported sender for DC 4



lmao -1/0

**Comment by TheKaram** [comment]
Hmmm, i tried it and it works but for some reason it print the error in `first_try.txt` file, however i tried to upload the downloaded file and it works.
i tried it another time after settings log level to info and it panic logs in `second_try.txt` i tried to reproduce it with debug log level but i couldn't.
also another 2 errors (include a panic) appeared you can see it in `third_try.txt` 

[first_try.txt](https://github.com/user-attachments/files/16512029/first_try.txt)
[second_try.txt](https://github.com/user-attachments/files/16512058/second_try.txt)
[third_try.txt](https://github.com/user-attachments/files/16512264/third_try.txt)

**Comment by AmarnathCJD** [comment]
ok seems minor error things

**Comment by TheKaram** [comment]
in the second and third try it panic and didn't complete the downloading

**Comment by AmarnathCJD** [comment]
> in the second and third try it panic and didn't complete the downloading

2nd is related to something other than this media related., 3rd is a bug in something I pushed yesterday.

**Comment by TheKaram** [comment]
oh ok
Thanks for the great work.
Can I get your Telegram username? I would like to give you a very small gift as a thank you for your effort in reacting quickly to issues

**Comment by TAMILVIP007** [comment]
@TheKaram @tamilvip007

**Comment by TheKaram** [comment]
> @TheKaram @TAMILVIP007

Nice try :rofl:

**Comment by TAMILVIP007** [comment]
@TheKaram join @RoseXChat btw

**Comment by AmarnathCJD** [comment]
> oh ok Thanks for the great work. Can I get your Telegram username? I would like to give you a very small gift as a thank you for your effort in reacting quickly to issues

@RoseLoverX 😹

**Comment by TAMILVIP007** [comment]
@AmarnathCJD dats scammin vro

**Comment by TheKaram** [comment]
> > oh ok Thanks for the great work. Can I get your Telegram username? I would like to give you a very small gift as a thank you for your effort in reacting quickly to issues
> 
> @RoseLoverX 😹

Check your DM
