### ISSUE TITLE
Concurrent map writes

### ISSUE THREAD

**Issue by kokoulin** [AmarnathCJD/gogram#147]
fatal error: concurrent map writes
on delete key from map c.dispatcher.activeAlbums

goroutine 7423 [running]:
github.com/amarnathcjd/gogram/telegram.(*Client).handleAlbum.func1()
        /Users/KokoulinNS/work/tlgrm-parse/vendor/github.com/amarnathcjd/gogram/telegram/updates.go:461 

Maybe add lock?

**Comment by AmarnathCJD** [comment]
alright

**Comment by frux** [comment]
Although I use v1.5.3 I ran into this issue. Looks like the problem stays there.
```
fatal error: concurrent map writes

goroutine 131 [running]:
internal/runtime/maps.fatal({0x10347146b?, 0x103719b40?})
        /opt/homebrew/Cellar/go/1.24.1/libexec/src/runtime/panic.go:1058 +0x20
github.com/amarnathcjd/gogram/telegram.(*Client).handleAlbum(_, {0x0, 0x0, 0x0, 0x0, 0x1, 0x0, 0x0, 0x0, 0x0, ...})
        /Users/frux/go/pkg/mod/github.com/amarnathcjd/gogram@v1.5.3/telegram/updates.go:491 +0x1a8
github.com/amarnathcjd/gogram/telegram.(*Client).handleMessageUpdate(0x1400014c480, {0x1038732d8?, 0x140001fe000})
        /Users/frux/go/pkg/mod/github.com/amarnathcjd/gogram@v1.5.3/telegram/updates.go:419 +0x100
created by github.com/amarnathcjd/gogram/telegram.HandleIncomingUpdates in goroutine 13
        /Users/frux/go/pkg/mod/github.com/amarnathcjd/gogram@v1.5.3/telegram/updates.go:1134 +0xcb8

goroutine 1 [sync.WaitGroup.Wait, 2 minutes]:
sync.runtime_SemacquireWaitGroup(0x140006b1b90?)
        /opt/homebrew/Cellar/go/1.24.1/libexec/src/runtime/sema.go:110 +0x2c
sync.(*WaitGroup).Wait(0x140005760b0)
        /opt/homebrew/Cellar/go/1.24.1/libexec/src/sync/waitgroup.go:118 +0x70
main.main()
        /Users/frux/Code/telegram-funnel-bot/main.go:104 +0x6c8

goroutine 5 [chan receive, 2 minutes]:
main.main.func1()
        /Users/frux/Code/telegram-funnel-bot/main.go:33 +0x90
created by main.main in goroutine 1
        /Users/frux/Code/telegram-funnel-bot/main.go:30 +0x178

goroutine 6 [select, 2 minutes]:
database/sql.(*DB).connectionOpener(0x1400038cb60, {0x103876880, 0x1400039a6e0})
        /opt/homebrew/Cellar/go/1.24.1/libexec/src/database/sql/sql.go:1261 +0x80
created by database/sql.OpenDB in goroutine 1
        /opt/homebrew/Cellar/go/1.24.1/libexec/src/database/sql/sql.go:841 +0x124

goroutine 50 [syscall, 2 minutes]:
os/signal.signal_recv()
        /opt/homebrew/Cellar/go/1.24.1/libexec/src/runtime/sigqueue.go:149 +0x2c
os/signal.loop()
        /opt/homebrew/Cellar/go/1.24.1/libexec/src/os/signal/signal_unix.go:23 +0x1c
created by os/signal.Notify.func1.1 in goroutine 5
        /opt/homebrew/Cellar/go/1.24.1/libexec/src/os/signal/signal.go:152 +0x28

goroutine 44 [select]:
tg-just-feed/app.(*App).Start(0x140005a02a0, {0x103876880, 0x1400039a4b0})
        /Users/frux/Code/telegram-funnel-bot/app/app.go:91 +0x620
main.main.func2()
        /Users/frux/Code/telegram-funnel-bot/main.go:88 +0x30
created by main.main in goroutine 1
        /Users/frux/Code/telegram-funnel-bot/main.go:87 +0x54c

goroutine 13 [select]:
github.com/amarnathcjd/gogram/internal/transport.(*Reader).Read(0x140001bd580, {0x14000022aa4, 0x1, 0x103d3e660?})
        /Users/frux/go/pkg/mod/github.com/amarnathcjd/gogram@v1.5.3/internal/transport/writer.go:59 +0x108
github.com/amarnathcjd/gogram/internal/transport.(*tcpConn).Read(0x140002104c8?, {0x14000022aa4?, 0x1?, 0x4?})
        /Users/frux/go/pkg/mod/github.com/amarnathcjd/gogram@v1.5.3/internal/transport/connection.go:84 +0x90
github.com/amarnathcjd/gogram/internal/mode.(*abridged).ReadMsg(0x1400003b6e0)
        /Users/frux/go/pkg/mod/github.com/amarnathcjd/gogram@v1.5.3/internal/mode/arbiged.go:62 +0x5c
github.com/amarnathcjd/gogram/internal/transport.(*transport).ReadMsg(0x1400057dd10)
        /Users/frux/go/pkg/mod/github.com/amarnathcjd/gogram@v1.5.3/internal/transport/transport.go:83 +0x30
github.com/amarnathcjd/gogram.(*MTProto).readMsg(0x1400017a420)
        /Users/frux/go/pkg/mod/github.com/amarnathcjd/gogram@v1.5.3/mtproto.go:680 +0x30
github.com/amarnathcjd/gogram.(*MTProto).startReadingResponses.func1()
        /Users/frux/go/pkg/mod/github.com/amarnathcjd/gogram@v1.5.3/mtproto.go:603 +0xa0
created by github.com/amarnathcjd/gogram.(*MTProto).startReadingResponses in goroutine 1
        /Users/frux/go/pkg/mod/github.com/amarnathcjd/gogram@v1.5.3/mtproto.go:592 +0x8c

goroutine 12 [IO wait]:
internal/poll.runtime_pollWait(0x10427cf10, 0x72)
        /opt/homebrew/Cellar/go/1.24.1/libexec/src/runtime/netpoll.go:351 +0xa0
internal/poll.(*pollDesc).wait(0x14000554480?, 0x14000022aa8?, 0x0)
        /opt/homebrew/Cellar/go/1.24.1/libexec/src/internal/poll/fd_poll_runtime.go:84 +0x28
internal/poll.(*pollDesc).waitRead(...)
        /opt/homebrew/Cellar/go/1.24.1/libexec/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0x14000554480, {0x14000022aa8, 0x1, 0x1})
        /opt/homebrew/Cellar/go/1.24.1/libexec/src/internal/poll/fd_unix.go:165 +0x1fc
net.(*netFD).Read(0x14000554480, {0x14000022aa8?, 0x140005a0340?, 0x14000612f44?})
        /opt/homebrew/Cellar/go/1.24.1/libexec/src/net/fd_posix.go:55 +0x28
net.(*conn).Read(0x140001106f8, {0x14000022aa8?, 0x14000612ee8?, 0x1031c1940?})
        /opt/homebrew/Cellar/go/1.24.1/libexec/src/net/net.go:194 +0x34
io.ReadAtLeast({0x103872780, 0x140001106f8}, {0x14000022aa8, 0x1, 0x1}, 0x1)
        /opt/homebrew/Cellar/go/1.24.1/libexec/src/io/io.go:335 +0xa0
io.ReadFull(...)
        /opt/homebrew/Cellar/go/1.24.1/libexec/src/io/io.go:354
github.com/amarnathcjd/gogram/internal/transport.(*Reader).begin(0x140001bd580)
        /Users/frux/go/pkg/mod/github.com/amarnathcjd/gogram@v1.5.3/internal/transport/writer.go:32 +0xd8
created by github.com/amarnathcjd/gogram/internal/transport.NewReader in goroutine 1
        /Users/frux/go/pkg/mod/github.com/amarnathcjd/gogram@v1.5.3/internal/transport/writer.go:92 +0x104

goroutine 14 [sleep]:
time.Sleep(0x6fc23ac00)
        /opt/homebrew/Cellar/go/1.24.1/libexec/src/runtime/time.go:338 +0x158
github.com/amarnathcjd/gogram.(*MTProto).longPing(0x1400017a420, {0x103876880, 0x1400016f3b0})
        /Users/frux/go/pkg/mod/github.com/amarnathcjd/gogram@v1.5.3/mtproto.go:575 +0x78
created by github.com/amarnathcjd/gogram.(*MTProto).CreateConnection in goroutine 1
        /Users/frux/go/pkg/mod/github.com/amarnathcjd/gogram@v1.5.3/mtproto.go:392 +0x60c

goroutine 65 [chan receive, 2 minutes]:
github.com/amarnathcjd/gogram/telegram.(*UpdateDispatcher).SortTrigger.func1()
        /Users/frux/go/pkg/mod/github.com/amarnathcjd/gogram@v1.5.3/telegram/updates.go:333 +0x3c
created by github.com/amarnathcjd/gogram/telegram.(*UpdateDispatcher).SortTrigger in goroutine 1
        /Users/frux/go/pkg/mod/github.com/amarnathcjd/gogram@v1.5.3/telegram/updates.go:332 +0xa0

goroutine 43 [chan receive, 2 minutes]:
github.com/amarnathcjd/gogram/telegram.(*UpdateDispatcher).SortTrigger.func1()
        /Users/frux/go/pkg/mod/github.com/amarnathcjd/gogram@v1.5.3/telegram/updates.go:333 +0x3c
created by github.com/amarnathcjd/gogram/telegram.(*UpdateDispatcher).SortTrigger in goroutine 1
        /Users/frux/go/pkg/mod/github.com/amarnathcjd/gogram@v1.5.3/telegram/updates.go:332 +0xa0

goroutine 71 [IO wait, 2 minutes]:
internal/poll.runtime_pollWait(0x10427cce0, 0x72)
        /opt/homebrew/Cellar/go/1.24.1/libexec/src/runtime/netpoll.go:351 +0xa0
internal/poll.(*pollDesc).wait(0x1400017e380?, 0x10377c9e0?, 0x0)
        /opt/homebrew/Cellar/go/1.24.1/libexec/src/internal/poll/fd_poll_runtime.go:84 +0x28
internal/poll.(*pollDesc).waitRead(...)
        /opt/homebrew/Cellar/go/1.24.1/libexec/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Accept(0x1400017e380)
        /opt/homebrew/Cellar/go/1.24.1/libexec/src/internal/poll/fd_unix.go:620 +0x24c
net.(*netFD).accept(0x1400017e380)
        /opt/homebrew/Cellar/go/1.24.1/libexec/src/net/fd_unix.go:172 +0x28
net.(*TCPListener).accept(0x140005e52c0)
        /opt/homebrew/Cellar/go/1.24.1/libexec/src/net/tcpsock_posix.go:159 +0x24
net.(*TCPListener).Accept(0x140005e52c0)
        /opt/homebrew/Cellar/go/1.24.1/libexec/src/net/tcpsock.go:380 +0x2c
net/http.(*Server).Serve(0x14000816100, {0x1038764b0, 0x140005e52c0})
        /opt/homebrew/Cellar/go/1.24.1/libexec/src/net/http/server.go:3424 +0x290
net/http.(*Server).ListenAndServe(0x14000816100)
        /opt/homebrew/Cellar/go/1.24.1/libexec/src/net/http/server.go:3350 +0x84
tg-just-feed/status.StartServer.func2()
        /Users/frux/Code/telegram-funnel-bot/status/server.go:42 +0x28
created by tg-just-feed/status.StartServer in goroutine 45
        /Users/frux/Code/telegram-funnel-bot/status/server.go:41 +0x12c

goroutine 15 [IO wait]:
internal/poll.runtime_pollWait(0x10427cdf8, 0x72)
        /opt/homebrew/Cellar/go/1.24.1/libexec/src/runtime/netpoll.go:351 +0xa0
internal/poll.(*pollDesc).wait(0x1400017e080?, 0x1400038836c?, 0x0)
        /opt/homebrew/Cellar/go/1.24.1/libexec/src/internal/poll/fd_poll_runtime.go:84 +0x28
internal/poll.(*pollDesc).waitRead(...)
        /opt/homebrew/Cellar/go/1.24.1/libexec/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0x1400017e080, {0x1400038836c, 0x1, 0x1})
        /opt/homebrew/Cellar/go/1.24.1/libexec/src/internal/poll/fd_unix.go:165 +0x1fc
net.(*netFD).Read(0x1400017e080, {0x1400038836c?, 0x140005a0040?, 0x140005b2f44?})
        /opt/homebrew/Cellar/go/1.24.1/libexec/src/net/fd_posix.go:55 +0x28
net.(*conn).Read(0x14000110148, {0x1400038836c?, 0x140005b2ee8?, 0x1031c1940?})
        /opt/homebrew/Cellar/go/1.24.1/libexec/src/net/net.go:194 +0x34
io.ReadAtLeast({0x103872780, 0x14000110148}, {0x1400038836c, 0x1, 0x1}, 0x1)
        /opt/homebrew/Cellar/go/1.24.1/libexec/src/io/io.go:335 +0xa0
io.ReadFull(...)
        /opt/homebrew/Cellar/go/1.24.1/libexec/src/io/io.go:354
github.com/amarnathcjd/gogram/internal/transport.(*Reader).begin(0x140006c1680)
        /Users/frux/go/pkg/mod/github.com/amarnathcjd/gogram@v1.5.3/internal/transport/writer.go:32 +0xd8
created by github.com/amarnathcjd/gogram/internal/transport.NewReader in goroutine 1
        /Users/frux/go/pkg/mod/github.com/amarnathcjd/gogram@v1.5.3/internal/transport/writer.go:92 +0x104

goroutine 16 [select]:
github.com/amarnathcjd/gogram/internal/transport.(*Reader).Read(0x140006c1680, {0x14000388368, 0x1, 0x103d3e660?})
        /Users/frux/go/pkg/mod/github.com/amarnathcjd/gogram@v1.5.3/internal/transport/writer.go:59 +0x108
github.com/amarnathcjd/gogram/internal/transport.(*tcpConn).Read(0x1400031a048?, {0x14000388368?, 0x1?, 0x4?})
        /Users/frux/go/pkg/mod/github.com/amarnathcjd/gogram@v1.5.3/internal/transport/connection.go:84 +0x90
github.com/amarnathcjd/gogram/internal/mode.(*abridged).ReadMsg(0x1400003a150)
        /Users/frux/go/pkg/mod/github.com/amarnathcjd/gogram@v1.5.3/internal/mode/arbiged.go:62 +0x5c
github.com/amarnathcjd/gogram/internal/transport.(*transport).ReadMsg(0x14000686060)
        /Users/frux/go/pkg/mod/github.com/amarnathcjd/gogram@v1.5.3/internal/transport/transport.go:83 +0x30
github.com/amarnathcjd/gogram.(*MTProto).readMsg(0x1400017a580)
        /Users/frux/go/pkg/mod/github.com/amarnathcjd/gogram@v1.5.3/mtproto.go:680 +0x30
github.com/amarnathcjd/gogram.(*MTProto).startReadingResponses.func1()
        /Users/frux/go/pkg/mod/github.com/amarnathcjd/gogram@v1.5.3/mtproto.go:603 +0xa0
created by github.com/amarnathcjd/gogram.(*MTProto).startReadingResponses in goroutine 1
        /Users/frux/go/pkg/mod/github.com/amarnathcjd/gogram@v1.5.3/mtproto.go:592 +0x8c

goroutine 81 [sleep]:
time.Sleep(0x6fc23ac00)
        /opt/homebrew/Cellar/go/1.24.1/libexec/src/runtime/time.go:338 +0x158
github.com/amarnathcjd/gogram.(*MTProto).longPing(0x1400017a580, {0x103876880, 0x1400039a0a0})
        /Users/frux/go/pkg/mod/github.com/amarnathcjd/gogram@v1.5.3/mtproto.go:575 +0x78
created by github.com/amarnathcjd/gogram.(*MTProto).CreateConnection in goroutine 1
        /Users/frux/go/pkg/mod/github.com/amarnathcjd/gogram@v1.5.3/mtproto.go:392 +0x60c

goroutine 45 [chan receive, 2 minutes]:
tg-just-feed/status.StartServer(0x140005a02a0, 0x14000550850, {0x103876880, 0x1400039a4b0})
        /Users/frux/Code/telegram-funnel-bot/status/server.go:50 +0x190
main.main.func3()
        /Users/frux/Code/telegram-funnel-bot/main.go:97 +0xec
created by main.main in goroutine 1
        /Users/frux/Code/telegram-funnel-bot/main.go:96 +0x5b4

goroutine 48 [sync.WaitGroup.Wait, 2 minutes]:
sync.runtime_SemacquireWaitGroup(0x14000224c40?)
        /opt/homebrew/Cellar/go/1.24.1/libexec/src/runtime/sema.go:110 +0x2c
sync.(*WaitGroup).Wait(0x1400014c2d8)
        /opt/homebrew/Cellar/go/1.24.1/libexec/src/sync/waitgroup.go:118 +0x70
github.com/amarnathcjd/gogram/telegram.(*Client).Idle(0x1400014c240)
        /Users/frux/go/pkg/mod/github.com/amarnathcjd/gogram@v1.5.3/telegram/client.go:610 +0xb8
tg-just-feed/telegram.(*Client).ListenUpdates(0x140005900e0, 0x1400010e9a0)
        /Users/frux/Code/telegram-funnel-bot/telegram/client.go:159 +0x554
created by tg-just-feed/app.(*App).Start in goroutine 44
        /Users/frux/Code/telegram-funnel-bot/app/app.go:85 +0x47c

goroutine 97 [sync.WaitGroup.Wait, 2 minutes]:
sync.runtime_SemacquireWaitGroup(0x14000224e00?)
        /opt/homebrew/Cellar/go/1.24.1/libexec/src/runtime/sema.go:110 +0x2c
sync.(*WaitGroup).Wait(0x1400014c518)
        /opt/homebrew/Cellar/go/1.24.1/libexec/src/sync/waitgroup.go:118 +0x70
github.com/amarnathcjd/gogram/telegram.(*Client).Idle(0x1400014c480)
        /Users/frux/go/pkg/mod/github.com/amarnathcjd/gogram@v1.5.3/telegram/client.go:610 +0xb8
tg-just-feed/telegram.(*Client).ListenUpdates(0x14000239100, 0x1400010e930)
        /Users/frux/Code/telegram-funnel-bot/telegram/client.go:159 +0x554
created by tg-just-feed/app.(*App).Start in goroutine 44
        /Users/frux/Code/telegram-funnel-bot/app/app.go:86 +0x4ec

goroutine 98 [chan receive, 2 minutes]:
github.com/amarnathcjd/gogram/telegram.(*Client).Idle.func1()
        /Users/frux/go/pkg/mod/github.com/amarnathcjd/gogram@v1.5.3/telegram/client.go:606 +0x88
created by github.com/amarnathcjd/gogram/telegram.(*Client).Idle in goroutine 97
        /Users/frux/go/pkg/mod/github.com/amarnathcjd/gogram@v1.5.3/telegram/client.go:603 +0x70

goroutine 84 [chan receive, 2 minutes]:
github.com/amarnathcjd/gogram/telegram.(*Client).Idle.func1()
        /Users/frux/go/pkg/mod/github.com/amarnathcjd/gogram@v1.5.3/telegram/client.go:606 +0x88
created by github.com/amarnathcjd/gogram/telegram.(*Client).Idle in goroutine 48
        /Users/frux/go/pkg/mod/github.com/amarnathcjd/gogram@v1.5.3/telegram/client.go:603 +0x70

goroutine 85 [chan receive, 2 minutes]:
github.com/amarnathcjd/gogram/telegram.(*Client).Idle.func2()
        /Users/frux/go/pkg/mod/github.com/amarnathcjd/gogram@v1.5.3/telegram/client.go:609 +0x58
created by github.com/amarnathcjd/gogram/telegram.(*Client).Idle in goroutine 48
        /Users/frux/go/pkg/mod/github.com/amarnathcjd/gogram@v1.5.3/telegram/client.go:609 +0xb0

goroutine 99 [chan receive, 2 minutes]:
github.com/amarnathcjd/gogram/telegram.(*Client).Idle.func2()
        /Users/frux/go/pkg/mod/github.com/amarnathcjd/gogram@v1.5.3/telegram/client.go:609 +0x58
created by github.com/amarnathcjd/gogram/telegram.(*Client).Idle in goroutine 97
        /Users/frux/go/pkg/mod/github.com/amarnathcjd/gogram@v1.5.3/telegram/client.go:609 +0xb0

goroutine 133 [sleep]:
time.Sleep(0x165a0bc00)
        /opt/homebrew/Cellar/go/1.24.1/libexec/src/runtime/time.go:338 +0x158
github.com/amarnathcjd/gogram/telegram.(*albumBox).WaitAndTrigger(0x140005aa000, 0x14000554100, 0x1400014c480)
        /Users/frux/go/pkg/mod/github.com/amarnathcjd/gogram@v1.5.3/telegram/updates.go:75 +0x44
github.com/amarnathcjd/gogram/telegram.(*Client).handleAlbum(_, {0x0, 0x0, 0x0, 0x0, 0x1, 0x0, 0x0, 0x0, 0x0, ...})
        /Users/frux/go/pkg/mod/github.com/amarnathcjd/gogram@v1.5.3/telegram/updates.go:492 +0x1e8
github.com/amarnathcjd/gogram/telegram.(*Client).handleMessageUpdate(0x1400014c480, {0x1038732d8?, 0x140001fe3c0})
        /Users/frux/go/pkg/mod/github.com/amarnathcjd/gogram@v1.5.3/telegram/updates.go:419 +0x100
created by github.com/amarnathcjd/gogram/telegram.HandleIncomingUpdates in goroutine 13
        /Users/frux/go/pkg/mod/github.com/amarnathcjd/gogram@v1.5.3/telegram/updates.go:1134 +0xcb8
exit status 2
```
