### ISSUE TITLE
Hold the loop

### ISSUE THREAD

**Issue by TAMILVIP007** [AmarnathCJD/gogram#17]
```2023/01/28 16:34:55 MTProto [INFO] Connection to 91.108.56.151:443/TcpFull complete!
panic: runtime error: index out of range [1] with length 1

goroutine 65 [running]:
AnimeUploader/plugins.CheckAnimeUpdate()
        D:/GoUploader/plugins/cron.go:29 +0x1b8
created by main.main
        D:/GoUploader/main.go:9 +0x2a
```

hold the mail loop instead of exiting if panicked

**Comment by TAMILVIP007** [comment]
```
func main() {
	bot := plugins.StartBot()
	go func() {
		defer func() {
			if r := recover(); r != nil {
				fmt.Println("Recovered from panic:", r)
			}
		}()
		plugins.CheckAnimeUpdate()
	}()
	bot.Idle()
}
```
workaround which i used rn
