### ISSUE TITLE
Handle error

### ISSUE THREAD

**Issue by stdkhai** [AmarnathCJD/gogram#25]
Handle error when length = 0 
```

panic: runtime error: index out of range [-1]

goroutine 1 [running]:
github.com/amarnathcjd/gogram/internal/aes_ige.pkcs5UnPadding(...)
        /pkg/mod/github.com/amarnathcjd/gogram@v0.0.0-20230204072323-ee7d323872bd/internal/aes_ige/aes_common.go:41
github.com/amarnathcjd/gogram/internal/aes_ige.DecryptAES({0xc00012e000, 0x0, 0x200}, {0x869011, 0x20})
        /pkg/mod/github.com/amarnathcjd/gogram@v0.0.0-20230204072323-ee7d323872bd/internal/aes_ige/aes_common.go:29 +0x1b7
github.com/amarnathcjd/gogram/telegram.(*CACHE).loadFromFile(0xc00009b530)
        /pkg/mod/github.com/amarnathcjd/gogram@v0.0.0-20230204072323-ee7d323872bd/telegram/cache.go:72 +0x48
github.com/amarnathcjd/gogram/telegram.NewCache()
        /pkg/mod/github.com/amarnathcjd/gogram@v0.0.0-20230204072323-ee7d323872bd/telegram/cache.go:98 +0x229
github.com/amarnathcjd/gogram/telegram.init()
        /pkg/mod/github.com/amarnathcjd/gogram@v0.0.0-20230204072323-ee7d323872bd/telegram/cache.go:83 +0x1d


```
https://github.com/AmarnathCJD/gogram/blob/ea13dc2073637bce9ad66ac1f1968764034d7f02/internal/aes_ige/aes_common.go#L39-L42

**Comment by AmarnathCJD** [comment]
@stdkhai Mhmm This is what happens if coded directly in GitHub 😹
